version: '3.1'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file:
      - .env
  db:
    image: postgres:12.17
    restart: always
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
